// internal/service/users.go
package service

import (
	"context"

	users "yourproject/gen/users"
	"yourproject/internal/repository"
)

// usersService implements users.Service generated by GOA
type usersService struct {
	userRepo repository.UserRepository
}

// NewUsersService constructs the GOA service with required repository dependencies
func NewUsersService(repo repository.UserRepository) users.Service {
	return &usersService{
		userRepo: repo,
	}
}

// Get implements the GOA generated service endpoint interface
func (s *usersService) Get(ctx context.Context, p *users.GetPayload) (*users.UserResult, error) {
	// 1. Call repository query layer
	dbUser, err := s.userRepo.GetByID(ctx, p.ID)
	if err != nil {
		// Map domain/DB errors to GOA error definitions if needed
		return nil, users.MakeNotFound(err)
	}

	// 2. Map domain model to GOA generated result type
	return &users.UserResult{
		ID:    dbUser.ID,
		Name:  dbUser.Name,
		Email: dbUser.Email,
	}, nil
}